# Generated by Django 3.0.2 on 2020-02-13 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUpdate',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Applying',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=50)),
                ('position', models.CharField(default='', max_length=50)),
                ('linkedin', models.CharField(default='', max_length=150)),
                ('github', models.CharField(default='', max_length=150)),
                ('portfolio', models.CharField(default='', max_length=150)),
                ('other', models.CharField(default='', max_length=150)),
                ('twitter', models.CharField(default='', max_length=150)),
                ('aspiration', models.CharField(default='', max_length=500)),
                ('skills', models.CharField(default='', max_length=500)),
                ('project', models.CharField(default='', max_length=500)),
                ('techstack', models.CharField(default='', max_length=500)),
                ('education', models.CharField(default='', max_length=500)),
                ('availablity', models.CharField(default='', max_length=500)),
                ('protfoliolink', models.CharField(default='', max_length=500)),
                ('opensourcecommit', models.CharField(default='', max_length=1000)),
                ('resume', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SelectIntern1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('task1name', models.CharField(default='', max_length=500)),
                ('task1link', models.CharField(default='', max_length=1000)),
                ('applicantEmail', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SelectIntern2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('task2name', models.CharField(default='', max_length=500)),
                ('task2link', models.CharField(default='', max_length=1000)),
                ('applicantEmail', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SelectIntern3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('task3name', models.CharField(default='', max_length=500)),
                ('task3link', models.CharField(default='', max_length=1000)),
                ('applicantEmail', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solution1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution1', models.CharField(default='', max_length=500)),
                ('appid', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Solution2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution2', models.CharField(default='', max_length=500)),
                ('appid', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Solution3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution2', models.CharField(default='', max_length=500)),
                ('appid', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
