# Generated by Django 3.0.2 on 2020-02-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution3',
            old_name='solution2',
            new_name='solution3',
        ),
    ]
